
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciamento-de-tarefas
spring.datasource.username=postgres
spring.datasource.password=admin



#----remove path info -- jsessionid-------
server.servlet.session.cookie.path=/
server.servlet.session.cookie.http-only=true
server.servlet.session.tracking-modes=cookie

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

logging.level.com.zaxxer.hikari=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=TRACE